services:
  api:
    container_name: sheetdeck-api
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    ports:
      - 8088:80
    env_file:
      - stack.env
    pull_policy: build
  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rK77WacWdSn746
        MYSQL_DATABASE: appdb
    ports:
        - 3306:3306
    volumes:
        - db-data:/var/lib/mysql
volumes:
    db-data: