lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    api_platform:
        check_path: /auth
        username_path: email
        password_path: password
    token_ttl: 3600
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER: ~
