#!/bin/sh
# husky
# ESLint et vue-tsc
echo "Running ESLint..."
(cd frontend && npx eslint .)

echo "Running vue-tsc..."
(cd frontend && npx vue-tsc --noEmit)

# echo "Running Cypress tests..."
# (cd frontend && npm test)

echo "Running PHP tests..."
(cd backend && symfony check:security && php ./vendor/bin/phpcbf src -- --standard=PSR12 && php ./vendor/bin/phpunit)