#!/bin/sh
# husky
# ESLint et vue-tsc
echo "Running ESLint..."
(cd frontend && npx eslint .)

echo "Running vue-tsc..."
(cd frontend && npx vue-tsc --noEmit)

echo "Running PHP tests..."
(cd backend && php ./vendor/bin/phpcbf src -- --standard=PSR12)