name: github-actions

on:
  push:
    branches: [ "the_tests" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
          docker-compose ps

      - name: Run PHPUnit
        run: docker-compose exec -T sheetdeck-api bin/phpunit

      # - name: Symfony CLI install
      #   run: curl -sS https://get.symfony.com/cli/installer | bash

      # - name: Install Composer dependencies
      #   run:
      #     symfony composer install --no-interaction

      # - name: Composer install
      #   run: composer install

      # - name: Security check
      #   run: php bin/console security:check

  # client-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         build: npm run build
  #         start: npm start