name: github-actions
on:
  push:
    branches: [ "the_tests" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Install Symfony CLI
        run: curl -sS https://get.symfony.com/cli/installer | bash

      - name: Security check
        run: symfony security:check